version: '3.8'

services:
  backend:
    build:
      context: ./mtuci-summer-parser
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=SummerParser
      - DB_USER=root
      - DB_PASSWORD=123qwe123
      - DB_PORT=5432
    command: ["flask", "run"]
    networks:
      - mynetwork

  frontend:
    build:
      context: ./mtuci-summer-parser-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    networks:
      - mynetwork

  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123qwe123
      - POSTGRES_DB=SummerParser
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge