FROM python:3.10-alpine

WORKDIR /app

RUN apk update && \
    apk add --no-cache gcc musl-dev linux-headers postgresql-dev

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000

EXPOSE 5000


CMD ["flask", "run"]
